version: '3.9'
services:
  www:
    image: nginx:latest
    restart: always
    ports:
      - ${HTTP_PORT:-80}:80
#      - ${HTTPS_PORT:-443}:443
    volumes:
      - ./configs/site.conf:/etc/nginx/conf.d/default.conf
      - ./wp_root:/app
      - ./logs:/var/log/nginx
    networks:
      - www_tier
    depends_on:
      - phpfpm
      - mariadb
  
  phpfpm:
    build:
      context: ./dockerfiles
      dockerfile: phpfpm.dockerfile
    restart: always
    volumes:
      - ./wp_root:/app
    networks:
      - php_tier
      - db_tier
      - www_tier

  mariadb:
    image: bitnami/mariadb:latest
    volumes:
      - ./data:/bitnami/mariadb/data
    #      - /configs/db.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
    restart: always
    env_file:
      - ./configs/db.env
    networks:
      - db_tier

#  redis:
#    image: bitnami/redis:latest
#    environment:
##      - ALLOW_EMPTY_PASSWORD=yes
#      - REDIS_IO_THREADS=4
#      - REDIS_IO_THREADS_DO_READS=yes
#      - REDIS_PASSWORD=loo3Aith@i
##    volumes:
##      - ./redis:/bitnami/redis/data
#    networks:
#      - php_tier

  composer:
    image: composer:latest
    volumes:
      - ./wp_root:/app
    depends_on:
      - phpfpm
    networks:
      - php_tier

networks:
  www_tier:
    driver: bridge
  php_tier:
    driver: bridge
  db_tier:
    driver: bridge

