version: '3.9'
services:
  pma:
    image: phpmyadmin
    links: 
      - mariadb:db
    ports:
      - 8080:80

networks:
  default:
    name: laravel-app_db_tier
    external: true


      #docker run --rm --name pmaserv -d --network laravel-app_db_tier --link laravel-app-mariadb-1:db -p 8080:80 phpmyadmin
