version: '3.9'
services:
  www:
    image: nginx:latest
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    env_file: .env
    volumes:
      - ./configs:/etc/nginx/conf.d
    networks:
      - edge_nginx

networks:
  edge_nginx:
    driver: bridge
