version: '3.9'
services:
  node1:
    image: "alpine:latest"
    networks:
      - net1
      - net2
    command: sh -c "echo \"check node_2:\" && ping node2 -c 4 && echo \"check node_3:\" && ping node3 -c 4"

  node2:
    image: "alpine:latest"
    networks:
      - net1
      - net3
    command: sh -c "sleep 15 && echo \"node_2 is done\""

  node3:
    image: "alpine:latest"
    networks:
      - net3
    command: sh -c "sleep 20 && echo \"node_3 is done\""

networks:
  net1:
    driver: bridge
  net2:
    driver: bridge
  net3:
    driver: bridge

